### ISSUE TITLE
Assessment questionnaire is not loading

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#3]
![Screenshot_20230711_140348_EmCare dev](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/122801361/05b08bf7-1f1c-4554-8c4e-ae6a701758d9)

**Comment by magp18** [comment]
Should be fixed

**Comment by kaledip** [comment]
retested and fixed
