### ISSUE TITLE
Some questions in Signs not appearing (older child)

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#32]
Question below need to appear if "Diarrhoea"= true
Sunken eyes, Skin pinch of abdomen, restless etc

**Comment by magp18** [comment]
I think I found the issue, will be in the next release as soon as the server is up again

**Comment by magp18** [comment]
Fixed on 0.0.124

**Comment by kaledip** [comment]
Retested and can be closed
