### ISSUE TITLE
Yes/No buttons seen before the Fast breathing question in Signs.

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#4]
![Screenshot_20230711_140310_EmCare dev](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/122801361/18b2d47b-362a-42b4-ad1a-4536728386cd)

**Comment by magp18** [comment]
Yes now it's Unconscious or Lethargic (which had been missing) and then you see "yes" "no"

**Comment by kaledip** [comment]
retested and can be closed
