### ISSUE TITLE
Childimage seen for question "Sex"in registration

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#5]
![Screenshot_20230711_101612_EmCare dev](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/122801361/b156b0b2-77f4-4118-b13f-79404cc781b2)

**Comment by ppanchal-argus** [comment]
This was resolved with l3 bundle update.
Note: @magp18  changing its status to testing.
