### ISSUE TITLE
Classifications issue

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#6]
All classifications appearing on the screen, default selected as "No".
Not able to proceed and submit classifications stage and move to treatment stage.
![Screenshot_20230718_114524_EmCare dev](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/122801361/b85c49d4-797b-4c0f-8ce0-7f94c0f5fb5e)

**Comment by ppanchal-argus** [comment]
![image](https://github.com/WorldHealthOrganization/smart-emcare-cmr/assets/99809012/1a1e7265-9e64-43c9-b586-125609f8ec48)
Not reflected in latest bundle, probably fixed with L3 change itself.

**Comment by kaledip** [comment]
retested
