### ISSUE TITLE
App crashing on new patient registration

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare-cmr#7]

**Comment by ppanchal-argus** [comment]
@magp18 Registration crash is due to binary url mismatch in questionnaire or resource not being present: com.google.android.fhir.db.ResourceNotFoundException: Resource not found with type Binary and id https:!

**Comment by delcroip** [comment]
should be fixed with 166

**Comment by ppanchal-argus** [comment]
@kaledip @delcroip I am unable to update the labels in the issue. Is that a permission issue?
